# Generated by Django 2.2.9 on 2020-01-28 12:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('visible', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Permission')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='RoleUtilisateur',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='connection_front.Ville', verbose_name='ville')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='concernte')),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='interesse')),
            ],
        ),
        migrations.CreateModel(
            name='MessagePrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('date_envoi', models.DateField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message privé',
                'verbose_name_plural': 'messages privé',
            },
        ),
        migrations.CreateModel(
            name='MessageGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('date_envoi', models.DateField()),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='expéditeur')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Groupe', verbose_name='groupe')),
            ],
            options={
                'verbose_name': 'message de groupe',
                'verbose_name_plural': 'messages de groupe',
            },
        ),
        migrations.AddField(
            model_name='groupe',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='créateur'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='membres', to='connection_front.Utilisateur', verbose_name='membres'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection_front.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invitation', models.DateTimeField(default=django.utils.timezone.now)),
                ('texte', models.CharField(max_length=100, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='destinataire')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Groupe', verbose_name='groupe')),
            ],
            options={
                'unique_together': {('groupe', 'destinataire')},
            },
        ),
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invitation', models.DateTimeField(default=django.utils.timezone.now)),
                ('texte', models.CharField(max_length=100, null=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='expediteur')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Groupe', verbose_name='groupe')),
            ],
            options={
                'verbose_name': "demande d'inscription",
                'verbose_name_plural': "demandes d'inscription",
                'unique_together': {('expediteur', 'groupe')},
            },
        ),
    ]
