# Generated by Django 3.0.1 on 2020-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('connection_front', '0003_delete_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
