# Generated by Django 3.0.1 on 2020-01-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0007_auto_20200108_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='texte',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='texte',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='connection_front.Ville', verbose_name='ville'),
        ),
    ]
