# Generated by Django 2.2.1 on 2020-01-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0008_auto_20200108_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='connection_front.Ville', verbose_name='ville'),
        ),
    ]
