# Generated by Django 2.2.1 on 2020-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0010_auto_20200109_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='option',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
