# Generated by Django 2.2.1 on 2020-01-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0012_utilisateur_image_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='./connection_front/ressources/'),
        ),
    ]
