# Generated by Django 2.2.1 on 2020-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0015_auto_20200110_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
