# Generated by Django 2.2.1 on 2020-01-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0016_auto_20200110_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_inscription',
        ),
    ]
