# Generated by Django 2.2.9 on 2020-01-22 10:32

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('connection_front', '0017_remove_utilisateur_date_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUtilisateur',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='demandeinscription',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='messagegroupe',
            name='groupe',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
    ]
