# Generated by Django 2.2.9 on 2020-01-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0018_auto_20200122_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('visible', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=False)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='créateur')),
            ],
        ),
    ]
