# Generated by Django 2.2.9 on 2020-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0021_demandeinscription_invitation_messagegroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='membre',
            field=models.ManyToManyField(blank=True, related_name='membre', to='connection_front.Utilisateur', verbose_name='membres'),
        ),
    ]
