# Generated by Django 2.2.9 on 2020-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0022_groupe_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='membre',
        ),
        migrations.AddField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='membres', to='connection_front.Utilisateur', verbose_name='membres'),
        ),
    ]
