# Generated by Django 2.2.9 on 2020-01-22 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0023_auto_20200122_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='date_invitation',
            field=models.DateField(default=datetime.datetime(2020, 1, 22, 15, 35, 53, 157006)),
        ),
    ]
