# Generated by Django 2.2.9 on 2020-01-22 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0024_auto_20200122_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='date_invitation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
