# Generated by Django 2.2.9 on 2020-01-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0026_auto_20200122_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='expediteur'),
        ),
    ]
