# Generated by Django 2.2.9 on 2020-01-22 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0028_auto_20200122_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='date_invitation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
