# Generated by Django 2.2.9 on 2020-01-23 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0029_auto_20200122_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_invitation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
