# Generated by Django 2.2.9 on 2020-01-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0030_auto_20200123_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('groupe', 'destinataire')},
        ),
    ]
