# Generated by Django 2.2.9 on 2020-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0031_auto_20200123_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='groupes', to='connection_front.Utilisateur', verbose_name='membres'),
        ),
    ]
