# Generated by Django 2.2.9 on 2020-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0032_auto_20200203_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='_utilisateur_groupes_+', to='connection_front.Groupe', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='_groupe_membres_+', to='connection_front.Utilisateur', verbose_name='membres'),
        ),
    ]
