# Generated by Django 2.2.9 on 2020-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0034_auto_20200203_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepte',
            field=models.BooleanField(null=True),
        ),
    ]
