# Generated by Django 2.2.9 on 2020-02-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0035_invitation_accepte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='membres',
        ),
    ]
