# Generated by Django 2.2.9 on 2020-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0037_membregroupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membregroupe',
            name='membre',
        ),
        migrations.AddField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='_groupe_membres_+', to='connection_front.MembreGroupe', verbose_name='membres'),
        ),
    ]
