# Generated by Django 2.2.9 on 2020-02-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0038_auto_20200204_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membregroupe',
            name='groupe',
        ),
    ]
