# Generated by Django 2.2.9 on 2020-02-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0039_remove_membregroupe_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='membregroupe',
            name='membre',
            field=models.ManyToManyField(blank=True, related_name='_membregroupe_membre_+', to='connection_front.Utilisateur', verbose_name='membre'),
        ),
    ]
