# Generated by Django 2.2.9 on 2020-02-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0042_auto_20200204_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membregroupe',
            name='groupe',
        ),
    ]
