# Generated by Django 2.2.9 on 2020-02-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0043_remove_membregroupe_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membregroupe',
            name='membre',
        ),
    ]
