# Generated by Django 2.2.9 on 2020-02-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0045_auto_20200204_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createur', models.BooleanField(default=False)),
                ('responsable', models.BooleanField(default=False)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Utilisateur', verbose_name='membre')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='_groupe_membres_+', to='connection_front.MembreGroupe', verbose_name='membres'),
        ),
    ]
