# Generated by Django 2.2.9 on 2020-02-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0046_auto_20200204_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='membregroupe',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connection_front.Groupe', verbose_name='groupe'),
            preserve_default=False,
        ),
    ]
