# Generated by Django 2.2.9 on 2020-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0047_membregroupe_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='membres',
            field=models.ManyToManyField(related_name='_groupe_membres_+', to='connection_front.MembreGroupe', verbose_name='membres'),
        ),
    ]
