# Generated by Django 2.2.9 on 2020-02-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0048_auto_20200204_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='membres',
        ),
    ]
