# Generated by Django 2.2.9 on 2020-02-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0049_remove_groupe_membres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='createur',
        ),
    ]
