# Generated by Django 2.2.9 on 2020-02-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0052_auto_20200210_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membregroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='connection_front.Groupe', verbose_name='groupe'),
        ),
    ]
