# Generated by Django 2.2.9 on 2020-02-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0053_auto_20200210_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groupes',
        ),
    ]
