# Generated by Django 2.2.9 on 2020-02-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0054_remove_utilisateur_groupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membregroupe',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='connection_front.Utilisateur', verbose_name='membre'),
        ),
    ]
