# Generated by Django 2.2.9 on 2020-02-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0055_auto_20200210_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
