# Generated by Django 2.2.9 on 2020-02-11 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection_front', '0056_auto_20200211_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroupe',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
